name: PR Validator
on:
  pull_request:
    branches:
    - Experimental-Mod-Pack
jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: "Validate SUMMARY"
        uses: actions/checkout@v2
        with:
          description-regex: '(\n|^)\s*`{0,3}SUMMARY: +(None|((Features|Content|Interface|Mods|Balance|Bugfixes|Performance|Infrastructure|Build|I18N) +".*"))`{0,3}\s*(\n|$)'
          description-regex-flags: 'i'
