on:
  push:
    branches:
    - master
    paths:
    - 'Documents'
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2.6.1
        with:
          TARGET_PATHS: "Documents"
          COMMIT_NAME: "TOC Generator"
          COMMIT_EMAIL: "noreply@example.invalid"
