travis encrypt 58c01ce7f85f3a7bf3ea2bd353a972710bc57083

addons:
  sonarcloud:
    organization: "thegoatgod"
    token:
      secure: "**************************" # encrypted value of your token

script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output <your clean build command>
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
